import welcomeImg from "@assets/stock_images/modern_mobile_app_on_2599db80.jpg";
import featuresImg from "@assets/stock_images/mobile_app_features__24cf7eff.jpg";
import notificationsImg from "@assets/stock_images/push_notification_be_12ad415d.jpg";
import securityImg from "@assets/stock_images/privacy_security_shi_9840be3c.jpg";
import successImg from "@assets/stock_images/success_celebration__0740591f.jpg";
import profileImg from "@assets/stock_images/user_profile_persona_e24692e8.jpg";
import communityImg from "@assets/stock_images/community_social_con_4ca37181.jpg";
import premiumImg from "@assets/stock_images/premium_upgrade_subs_06a75f89.jpg";
import type { Widget, ScreenLayout } from "./widget-editor/widget-types";

export interface OnboardingTemplate {
  id: string;
  name: string;
  description: string;
  category: "welcome" | "features" | "notifications" | "security" | "success" | "profile" | "community" | "premium";
  style: "minimal" | "gradient" | "dark" | "colorful" | "modern" | "corporate";
  previewImage: string;
  screens: {
    title: string;
    description: string;
    widgets: Widget[];
    layout: ScreenLayout;
  }[];
}

export const onboardingTemplates: OnboardingTemplate[] = [
  {
    id: "welcome-minimal",
    name: "Welcome - Minimal",
    description: "Clean and simple welcome screen with centered content",
    category: "welcome",
    style: "minimal",
    previewImage: welcomeImg,
    screens: [
      {
        title: "Welcome",
        description: "Get started with our app",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 40,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "image",
            order: 1,
            url: welcomeImg,
            width: "200px",
            height: "200px",
            objectFit: "cover",
            borderRadius: 100,
            name: "Welcome Image",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Welcome to App",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Your journey starts here. Discover amazing features that will change the way you work.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "w7",
            type: "button",
            order: 6,
            label: "Get Started",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "features-gradient",
    name: "Features - Gradient",
    description: "Showcase features with a beautiful gradient background",
    category: "features",
    style: "gradient",
    previewImage: featuresImg,
    screens: [
      {
        title: "Discover Features",
        description: "Explore what makes us special",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "image",
            order: 1,
            url: featuresImg,
            width: "100%",
            height: "220px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Features Image",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Powerful Features",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Everything you need to boost your productivity and achieve your goals faster.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.8)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w7",
            type: "button",
            order: 6,
            label: "Continue",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#ffffff",
            textColor: "#6366f1",
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#6366f1", position: 0 },
              { color: "#8b5cf6", position: 50 },
              { color: "#a855f7", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "notifications-modern",
    name: "Notifications - Modern",
    description: "Ask for notification permissions with style",
    category: "notifications",
    style: "modern",
    previewImage: notificationsImg,
    screens: [
      {
        title: "Stay Updated",
        description: "Enable notifications",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "icon",
            order: 1,
            iconName: "Bell",
            size: 64,
            color: "#f59e0b",
            backgroundColor: "#fef3c7",
            backgroundRadius: 32,
            name: "Bell Icon",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Stay in the Loop",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Get instant updates about important events, messages, and more. We promise not to spam you!",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 32,
            name: "Spacer",
          },
          {
            id: "w7",
            type: "image",
            order: 6,
            url: notificationsImg,
            width: "100%",
            height: "160px",
            objectFit: "cover",
            borderRadius: 12,
            name: "Notification Image",
          },
          {
            id: "w8",
            type: "spacer",
            order: 7,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w9",
            type: "button",
            order: 8,
            label: "Enable Notifications",
            variant: "primary",
            fullWidth: true,
            action: "custom",
            actionValue: "requestNotifications",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#f59e0b",
            name: "Primary Button",
          },
          {
            id: "w10",
            type: "button",
            order: 9,
            label: "Maybe Later",
            variant: "ghost",
            fullWidth: true,
            action: "next",
            fontSize: 14,
            fontWeight: "500",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "security-dark",
    name: "Security - Dark",
    description: "Privacy-focused screen with dark theme",
    category: "security",
    style: "dark",
    previewImage: securityImg,
    screens: [
      {
        title: "Your Privacy Matters",
        description: "We keep your data safe",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 40,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "icon",
            order: 1,
            iconName: "Shield",
            size: 72,
            color: "#10b981",
            name: "Shield Icon",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 20,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Your Privacy is Protected",
            fontSize: 24,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "We use end-to-end encryption and never share your data with third parties.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#9ca3af",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w7",
            type: "image",
            order: 6,
            url: securityImg,
            width: "100%",
            height: "180px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Security Image",
          },
          {
            id: "w8",
            type: "spacer",
            order: 7,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w9",
            type: "button",
            order: 8,
            label: "I Understand",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#10b981",
            textColor: "#ffffff",
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#111827",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "success-colorful",
    name: "Success - Colorful",
    description: "Celebrate completion with vibrant colors",
    category: "success",
    style: "colorful",
    previewImage: successImg,
    screens: [
      {
        title: "You're All Set!",
        description: "Welcome aboard",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 32,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "image",
            order: 1,
            url: successImg,
            width: "100%",
            height: "220px",
            objectFit: "cover",
            borderRadius: 20,
            name: "Success Image",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "icon",
            order: 3,
            iconName: "PartyPopper",
            size: 48,
            color: "#f43f5e",
            name: "Celebration Icon",
          },
          {
            id: "w5",
            type: "spacer",
            order: 4,
            height: 16,
            name: "Spacer",
          },
          {
            id: "w6",
            type: "text",
            order: 5,
            content: "You're All Set!",
            fontSize: 28,
            fontWeight: "800",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w7",
            type: "text",
            order: 6,
            content: "Congratulations! You've completed the setup. Let's start exploring.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w8",
            type: "spacer",
            order: 7,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w9",
            type: "button",
            order: 8,
            label: "Start Exploring",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundGradient: {
              enabled: true,
              type: "linear",
              angle: 90,
              stops: [
                { color: "#f43f5e", position: 0 },
                { color: "#ec4899", position: 100 },
              ],
            },
            textColor: "#ffffff",
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#fdf2f8",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "profile-modern",
    name: "Profile - Modern",
    description: "Personalization setup with modern design",
    category: "profile",
    style: "modern",
    previewImage: profileImg,
    screens: [
      {
        title: "Personalize Your Experience",
        description: "Set up your profile",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 40,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "image",
            order: 1,
            url: profileImg,
            width: "120px",
            height: "120px",
            objectFit: "cover",
            borderRadius: 60,
            name: "Profile Image",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Make It Yours",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Customize your profile and preferences to get a personalized experience tailored just for you.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 32,
            name: "Spacer",
          },
          {
            id: "w7",
            type: "divider",
            order: 6,
            color: "#e5e7eb",
            thickness: 1,
            style: "solid",
            width: "100%",
            name: "Divider",
          },
          {
            id: "w8",
            type: "spacer",
            order: 7,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w9",
            type: "button",
            order: 8,
            label: "Set Up Profile",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Primary Button",
          },
          {
            id: "w10",
            type: "button",
            order: 9,
            label: "Skip for Now",
            variant: "outline",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 14,
            fontWeight: "500",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "community-corporate",
    name: "Community - Corporate",
    description: "Professional community introduction",
    category: "community",
    style: "corporate",
    previewImage: communityImg,
    screens: [
      {
        title: "Join Our Community",
        description: "Connect with others",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 32,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "image",
            order: 1,
            url: communityImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 12,
            name: "Community Image",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Join Our Community",
            fontSize: 24,
            fontWeight: "600",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Connect with thousands of professionals. Share ideas, learn from experts, and grow together.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#4b5563",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 20,
            name: "Spacer",
          },
          {
            id: "w7",
            type: "icon",
            order: 6,
            iconName: "Users",
            size: 40,
            color: "#3b82f6",
            name: "Users Icon",
          },
          {
            id: "w8",
            type: "text",
            order: 7,
            content: "50,000+ Members",
            fontSize: 14,
            fontWeight: "600",
            textAlign: "center",
            color: "#3b82f6",
            fontFamily: "Inter",
            name: "Members Count",
          },
          {
            id: "w9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w10",
            type: "button",
            order: 9,
            label: "Join Community",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 8,
            fontSize: 16,
            fontWeight: "600",
            height: 48,
            backgroundColor: "#1e40af",
            textColor: "#ffffff",
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#f8fafc",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "premium-gradient",
    name: "Premium - Gradient",
    description: "Premium upgrade screen with luxury feel",
    category: "premium",
    style: "gradient",
    previewImage: premiumImg,
    screens: [
      {
        title: "Go Premium",
        description: "Unlock all features",
        widgets: [
          {
            id: "w1",
            type: "spacer",
            order: 0,
            height: 40,
            name: "Top Spacer",
          },
          {
            id: "w2",
            type: "icon",
            order: 1,
            iconName: "Crown",
            size: 64,
            color: "#fbbf24",
            name: "Crown Icon",
          },
          {
            id: "w3",
            type: "spacer",
            order: 2,
            height: 20,
            name: "Spacer",
          },
          {
            id: "w4",
            type: "text",
            order: 3,
            content: "Unlock Premium",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w5",
            type: "text",
            order: 4,
            content: "Get unlimited access to all features, priority support, and exclusive content.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.85)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w6",
            type: "spacer",
            order: 5,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w7",
            type: "image",
            order: 6,
            url: premiumImg,
            width: "100%",
            height: "160px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Premium Image",
          },
          {
            id: "w8",
            type: "spacer",
            order: 7,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w9",
            type: "button",
            order: 8,
            label: "Upgrade Now - $9.99/mo",
            variant: "custom",
            fullWidth: true,
            action: "purchase",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#fbbf24",
            textColor: "#1f2937",
            name: "Purchase Button",
          },
          {
            id: "w10",
            type: "button",
            order: 9,
            label: "Continue with Free",
            variant: "ghost",
            fullWidth: true,
            action: "next",
            fontSize: 14,
            fontWeight: "500",
            textColor: "rgba(255,255,255,0.8)",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 180,
            stops: [
              { color: "#1f2937", position: 0 },
              { color: "#111827", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
];

export function getTemplatesByCategory(category: OnboardingTemplate["category"]) {
  return onboardingTemplates.filter((t) => t.category === category);
}

export function getTemplatesByStyle(style: OnboardingTemplate["style"]) {
  return onboardingTemplates.filter((t) => t.style === style);
}
