import welcomeImg from "@assets/stock_images/modern_mobile_app_on_2599db80.jpg";
import featuresImg from "@assets/stock_images/mobile_app_features__24cf7eff.jpg";
import notificationsImg from "@assets/stock_images/push_notification_be_12ad415d.jpg";
import securityImg from "@assets/stock_images/privacy_security_shi_9840be3c.jpg";
import successImg from "@assets/stock_images/success_celebration__0740591f.jpg";
import profileImg from "@assets/stock_images/user_profile_persona_e24692e8.jpg";
import communityImg from "@assets/stock_images/community_social_con_4ca37181.jpg";
import premiumImg from "@assets/stock_images/premium_upgrade_subs_06a75f89.jpg";
import type { Widget, ScreenLayout } from "./widget-editor/widget-types";

export interface OnboardingTemplate {
  id: string;
  name: string;
  description: string;
  category: "welcome" | "features" | "notifications" | "security" | "success" | "profile" | "community" | "premium";
  style: "minimal" | "gradient" | "dark" | "colorful" | "modern" | "corporate";
  previewImage: string;
  screens: {
    title: string;
    description: string;
    widgets: Widget[];
    layout: ScreenLayout;
  }[];
}

export const onboardingTemplates: OnboardingTemplate[] = [
  {
    id: "welcome-minimal",
    name: "Welcome - Minimal",
    description: "Clean 3-screen onboarding with welcome, features and get started",
    category: "welcome",
    style: "minimal",
    previewImage: welcomeImg,
    screens: [
      {
        title: "Welcome",
        description: "Get started with our app",
        widgets: [
          {
            id: "w1-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "w1-2",
            type: "image",
            order: 1,
            url: welcomeImg,
            width: "180px",
            height: "180px",
            objectFit: "cover",
            borderRadius: 90,
            name: "Welcome Image",
          },
          {
            id: "w1-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "w1-4",
            type: "text",
            order: 3,
            content: "Welcome to App",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "w1-6",
            type: "text",
            order: 5,
            content: "Your journey starts here. Discover amazing features that will change the way you work.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w1-7",
            type: "spacer",
            order: 6,
            height: 48,
            name: "Bottom Spacer",
          },
          {
            id: "w1-8",
            type: "button",
            order: 7,
            label: "Get Started",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Discover Features",
        description: "What you can do",
        widgets: [
          {
            id: "w2-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "w2-2",
            type: "icon",
            order: 1,
            iconName: "Sparkles",
            size: 56,
            color: "#6366f1",
            name: "Sparkles Icon",
          },
          {
            id: "w2-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w2-4",
            type: "text",
            order: 3,
            content: "Powerful Features",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w2-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "w2-6",
            type: "text",
            order: 5,
            content: "Everything you need to boost productivity",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Subtitle",
          },
          {
            id: "w2-7",
            type: "spacer",
            order: 6,
            height: 32,
            name: "Spacer",
          },
          {
            id: "w2-8",
            type: "image",
            order: 7,
            url: featuresImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Features Image",
          },
          {
            id: "w2-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w2-10",
            type: "button",
            order: 9,
            label: "Continue",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Ready to Start",
        description: "Let's begin",
        widgets: [
          {
            id: "w3-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "w3-2",
            type: "icon",
            order: 1,
            iconName: "Rocket",
            size: 64,
            color: "#10b981",
            name: "Rocket Icon",
          },
          {
            id: "w3-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "w3-4",
            type: "text",
            order: 3,
            content: "You're All Set!",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "w3-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "w3-6",
            type: "text",
            order: 5,
            content: "Start exploring and discover everything our app has to offer.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "w3-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Spacer",
          },
          {
            id: "w3-8",
            type: "image",
            order: 7,
            url: successImg,
            width: "100%",
            height: "180px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Success Image",
          },
          {
            id: "w3-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "w3-10",
            type: "button",
            order: 9,
            label: "Start Exploring",
            variant: "primary",
            fullWidth: true,
            action: "close",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#10b981",
            name: "Primary Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "features-gradient",
    name: "Features - Gradient",
    description: "3 screens showcasing features with gradient backgrounds",
    category: "features",
    style: "gradient",
    previewImage: featuresImg,
    screens: [
      {
        title: "Feature 1 - Speed",
        description: "Lightning fast performance",
        widgets: [
          {
            id: "fg1-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "fg1-2",
            type: "icon",
            order: 1,
            iconName: "Zap",
            size: 72,
            color: "#ffffff",
            name: "Speed Icon",
          },
          {
            id: "fg1-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "fg1-4",
            type: "text",
            order: 3,
            content: "Lightning Fast",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "fg1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "fg1-6",
            type: "text",
            order: 5,
            content: "Experience blazing speed with our optimized performance. No more waiting around.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.85)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "fg1-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Spacer",
          },
          {
            id: "fg1-8",
            type: "image",
            order: 7,
            url: featuresImg,
            width: "100%",
            height: "180px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Feature Image",
          },
          {
            id: "fg1-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "fg1-10",
            type: "button",
            order: 9,
            label: "Next",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#ffffff",
            textColor: "#6366f1",
            name: "Next Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#6366f1", position: 0 },
              { color: "#8b5cf6", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Feature 2 - Security",
        description: "Your data is safe",
        widgets: [
          {
            id: "fg2-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "fg2-2",
            type: "icon",
            order: 1,
            iconName: "Shield",
            size: 72,
            color: "#ffffff",
            name: "Shield Icon",
          },
          {
            id: "fg2-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "fg2-4",
            type: "text",
            order: 3,
            content: "Bank-Level Security",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "fg2-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "fg2-6",
            type: "text",
            order: 5,
            content: "Your data is encrypted with enterprise-grade security. We never share your information.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.85)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "fg2-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Spacer",
          },
          {
            id: "fg2-8",
            type: "image",
            order: 7,
            url: securityImg,
            width: "100%",
            height: "180px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Security Image",
          },
          {
            id: "fg2-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "fg2-10",
            type: "button",
            order: 9,
            label: "Next",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#ffffff",
            textColor: "#10b981",
            name: "Next Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#10b981", position: 0 },
              { color: "#059669", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Feature 3 - Sync",
        description: "Always in sync",
        widgets: [
          {
            id: "fg3-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "fg3-2",
            type: "icon",
            order: 1,
            iconName: "Cloud",
            size: 72,
            color: "#ffffff",
            name: "Cloud Icon",
          },
          {
            id: "fg3-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "fg3-4",
            type: "text",
            order: 3,
            content: "Seamless Sync",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "fg3-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "fg3-6",
            type: "text",
            order: 5,
            content: "Access your data from anywhere. All your devices stay perfectly synchronized.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.85)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "fg3-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Spacer",
          },
          {
            id: "fg3-8",
            type: "image",
            order: 7,
            url: communityImg,
            width: "100%",
            height: "180px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Sync Image",
          },
          {
            id: "fg3-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "fg3-10",
            type: "button",
            order: 9,
            label: "Get Started",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#ffffff",
            textColor: "#3b82f6",
            name: "Start Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#3b82f6", position: 0 },
              { color: "#1d4ed8", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "notifications-modern",
    name: "Notifications - Modern",
    description: "2 screens: intro and notification permission request",
    category: "notifications",
    style: "modern",
    previewImage: notificationsImg,
    screens: [
      {
        title: "Stay Connected",
        description: "Never miss important updates",
        widgets: [
          {
            id: "nm1-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "nm1-2",
            type: "image",
            order: 1,
            url: notificationsImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 20,
            name: "Notification Image",
          },
          {
            id: "nm1-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "nm1-4",
            type: "text",
            order: 3,
            content: "Stay Connected",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "nm1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "nm1-6",
            type: "text",
            order: 5,
            content: "Get real-time updates about what matters most to you. Never miss an important moment.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "nm1-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "nm1-8",
            type: "button",
            order: 7,
            label: "Continue",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#f59e0b",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#fffbeb",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Enable Notifications",
        description: "Turn on notifications",
        widgets: [
          {
            id: "nm2-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "nm2-2",
            type: "icon",
            order: 1,
            iconName: "Bell",
            size: 80,
            color: "#f59e0b",
            backgroundColor: "#fef3c7",
            backgroundRadius: 40,
            name: "Bell Icon",
          },
          {
            id: "nm2-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "nm2-4",
            type: "text",
            order: 3,
            content: "Turn On Notifications",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "nm2-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "nm2-6",
            type: "text",
            order: 5,
            content: "We'll only send you the most important updates. You can customize your preferences anytime.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "nm2-7",
            type: "spacer",
            order: 6,
            height: 48,
            name: "Bottom Spacer",
          },
          {
            id: "nm2-8",
            type: "button",
            order: 7,
            label: "Enable Notifications",
            variant: "primary",
            fullWidth: true,
            action: "custom",
            actionValue: "requestNotifications",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#f59e0b",
            name: "Enable Button",
          },
          {
            id: "nm2-9",
            type: "spacer",
            order: 8,
            height: 12,
            name: "Spacer",
          },
          {
            id: "nm2-10",
            type: "button",
            order: 9,
            label: "Maybe Later",
            variant: "ghost",
            fullWidth: true,
            action: "close",
            fontSize: 14,
            fontWeight: "500",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "security-dark",
    name: "Security - Dark",
    description: "2 screens: privacy intro and data protection",
    category: "security",
    style: "dark",
    previewImage: securityImg,
    screens: [
      {
        title: "Your Data, Protected",
        description: "Security first",
        widgets: [
          {
            id: "sd1-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "sd1-2",
            type: "image",
            order: 1,
            url: securityImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 20,
            name: "Security Image",
          },
          {
            id: "sd1-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "sd1-4",
            type: "text",
            order: 3,
            content: "Your Data, Protected",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "sd1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "sd1-6",
            type: "text",
            order: 5,
            content: "We use industry-leading security measures to keep your information safe and private.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#9ca3af",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "sd1-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "sd1-8",
            type: "button",
            order: 7,
            label: "Learn More",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#10b981",
            textColor: "#ffffff",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#111827",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Privacy Promise",
        description: "Our commitment",
        widgets: [
          {
            id: "sd2-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "sd2-2",
            type: "icon",
            order: 1,
            iconName: "ShieldCheck",
            size: 80,
            color: "#10b981",
            name: "Shield Icon",
          },
          {
            id: "sd2-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "sd2-4",
            type: "text",
            order: 3,
            content: "Our Privacy Promise",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "sd2-5",
            type: "spacer",
            order: 4,
            height: 16,
            name: "Spacer",
          },
          {
            id: "sd2-6",
            type: "text",
            order: 5,
            content: "End-to-end encryption",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#34d399",
            fontFamily: "Inter",
            name: "Feature 1",
          },
          {
            id: "sd2-7",
            type: "spacer",
            order: 6,
            height: 8,
            name: "Spacer",
          },
          {
            id: "sd2-8",
            type: "text",
            order: 7,
            content: "No data sharing with third parties",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#34d399",
            fontFamily: "Inter",
            name: "Feature 2",
          },
          {
            id: "sd2-9",
            type: "spacer",
            order: 8,
            height: 8,
            name: "Spacer",
          },
          {
            id: "sd2-10",
            type: "text",
            order: 9,
            content: "GDPR & CCPA compliant",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#34d399",
            fontFamily: "Inter",
            name: "Feature 3",
          },
          {
            id: "sd2-11",
            type: "spacer",
            order: 10,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "sd2-12",
            type: "button",
            order: 11,
            label: "I Understand",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#10b981",
            textColor: "#ffffff",
            name: "Confirm Button",
          },
        ],
        layout: {
          backgroundColor: "#1f2937",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "success-colorful",
    name: "Success - Colorful",
    description: "2 screens: achievement and completion celebration",
    category: "success",
    style: "colorful",
    previewImage: successImg,
    screens: [
      {
        title: "Great Progress",
        description: "You're doing amazing",
        widgets: [
          {
            id: "sc1-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "sc1-2",
            type: "image",
            order: 1,
            url: successImg,
            width: "100%",
            height: "220px",
            objectFit: "cover",
            borderRadius: 24,
            name: "Success Image",
          },
          {
            id: "sc1-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "sc1-4",
            type: "icon",
            order: 3,
            iconName: "Star",
            size: 48,
            color: "#f43f5e",
            name: "Star Icon",
          },
          {
            id: "sc1-5",
            type: "spacer",
            order: 4,
            height: 16,
            name: "Spacer",
          },
          {
            id: "sc1-6",
            type: "text",
            order: 5,
            content: "Amazing Progress!",
            fontSize: 28,
            fontWeight: "800",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "sc1-7",
            type: "spacer",
            order: 6,
            height: 12,
            name: "Spacer",
          },
          {
            id: "sc1-8",
            type: "text",
            order: 7,
            content: "You're on your way to greatness. Just one more step to complete your setup.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "sc1-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "sc1-10",
            type: "button",
            order: 9,
            label: "Complete Setup",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundGradient: {
              enabled: true,
              type: "linear",
              angle: 90,
              stops: [
                { color: "#f43f5e", position: 0 },
                { color: "#ec4899", position: 100 },
              ],
            },
            textColor: "#ffffff",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#fff1f2",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Congratulations",
        description: "You did it!",
        widgets: [
          {
            id: "sc2-1",
            type: "spacer",
            order: 0,
            height: 80,
            name: "Top Spacer",
          },
          {
            id: "sc2-2",
            type: "icon",
            order: 1,
            iconName: "PartyPopper",
            size: 96,
            color: "#f43f5e",
            name: "Party Icon",
          },
          {
            id: "sc2-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "sc2-4",
            type: "text",
            order: 3,
            content: "Congratulations!",
            fontSize: 32,
            fontWeight: "800",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "sc2-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "sc2-6",
            type: "text",
            order: 5,
            content: "You've successfully completed the setup. Time to explore everything we have to offer!",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "sc2-7",
            type: "spacer",
            order: 6,
            height: 48,
            name: "Bottom Spacer",
          },
          {
            id: "sc2-8",
            type: "button",
            order: 7,
            label: "Start Exploring",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 16,
            fontSize: 18,
            fontWeight: "700",
            height: 56,
            backgroundGradient: {
              enabled: true,
              type: "linear",
              angle: 90,
              stops: [
                { color: "#ec4899", position: 0 },
                { color: "#8b5cf6", position: 100 },
              ],
            },
            textColor: "#ffffff",
            name: "Start Button",
          },
        ],
        layout: {
          backgroundColor: "#fdf2f8",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "profile-modern",
    name: "Profile - Modern",
    description: "3 screens: intro, personalization and preferences",
    category: "profile",
    style: "modern",
    previewImage: profileImg,
    screens: [
      {
        title: "Let's Personalize",
        description: "Make it yours",
        widgets: [
          {
            id: "pm1-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "pm1-2",
            type: "image",
            order: 1,
            url: profileImg,
            width: "140px",
            height: "140px",
            objectFit: "cover",
            borderRadius: 70,
            name: "Profile Image",
          },
          {
            id: "pm1-3",
            type: "spacer",
            order: 2,
            height: 28,
            name: "Spacer",
          },
          {
            id: "pm1-4",
            type: "text",
            order: 3,
            content: "Let's Get Personal",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pm1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pm1-6",
            type: "text",
            order: 5,
            content: "Set up your profile to get a customized experience that's uniquely yours.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "pm1-7",
            type: "spacer",
            order: 6,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "pm1-8",
            type: "button",
            order: 7,
            label: "Set Up Profile",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Continue Button",
          },
          {
            id: "pm1-9",
            type: "spacer",
            order: 8,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pm1-10",
            type: "button",
            order: 9,
            label: "Skip for Now",
            variant: "ghost",
            fullWidth: true,
            action: "close",
            fontSize: 14,
            fontWeight: "500",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Your Interests",
        description: "Tell us about yourself",
        widgets: [
          {
            id: "pm2-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "pm2-2",
            type: "icon",
            order: 1,
            iconName: "Heart",
            size: 64,
            color: "#ec4899",
            name: "Heart Icon",
          },
          {
            id: "pm2-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "pm2-4",
            type: "text",
            order: 3,
            content: "What Interests You?",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pm2-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pm2-6",
            type: "text",
            order: 5,
            content: "Select your interests so we can personalize your feed and recommendations.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "pm2-7",
            type: "spacer",
            order: 6,
            height: 32,
            name: "Spacer",
          },
          {
            id: "pm2-8",
            type: "image",
            order: 7,
            url: featuresImg,
            width: "100%",
            height: "160px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Interests Image",
          },
          {
            id: "pm2-9",
            type: "spacer",
            order: 8,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "pm2-10",
            type: "button",
            order: 9,
            label: "Continue",
            variant: "primary",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#fdf2f8",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "All Set",
        description: "Profile complete",
        widgets: [
          {
            id: "pm3-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "pm3-2",
            type: "icon",
            order: 1,
            iconName: "CheckCircle",
            size: 80,
            color: "#10b981",
            name: "Check Icon",
          },
          {
            id: "pm3-3",
            type: "spacer",
            order: 2,
            height: 28,
            name: "Spacer",
          },
          {
            id: "pm3-4",
            type: "text",
            order: 3,
            content: "Profile Complete!",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pm3-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pm3-6",
            type: "text",
            order: 5,
            content: "Your personalized experience is ready. Enjoy content tailored just for you!",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "pm3-7",
            type: "spacer",
            order: 6,
            height: 48,
            name: "Bottom Spacer",
          },
          {
            id: "pm3-8",
            type: "button",
            order: 7,
            label: "Start Exploring",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#10b981",
            textColor: "#ffffff",
            name: "Start Button",
          },
        ],
        layout: {
          backgroundColor: "#ecfdf5",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "community-corporate",
    name: "Community - Corporate",
    description: "3 screens: intro, benefits and join",
    category: "community",
    style: "corporate",
    previewImage: communityImg,
    screens: [
      {
        title: "Join Our Network",
        description: "Professional community",
        widgets: [
          {
            id: "cc1-1",
            type: "spacer",
            order: 0,
            height: 40,
            name: "Top Spacer",
          },
          {
            id: "cc1-2",
            type: "image",
            order: 1,
            url: communityImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 16,
            name: "Community Image",
          },
          {
            id: "cc1-3",
            type: "spacer",
            order: 2,
            height: 28,
            name: "Spacer",
          },
          {
            id: "cc1-4",
            type: "text",
            order: 3,
            content: "Join Our Network",
            fontSize: 26,
            fontWeight: "600",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "cc1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "cc1-6",
            type: "text",
            order: 5,
            content: "Connect with industry leaders, share insights, and accelerate your professional growth.",
            fontSize: 15,
            fontWeight: "400",
            textAlign: "center",
            color: "#4b5563",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "cc1-7",
            type: "spacer",
            order: 6,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "cc1-8",
            type: "button",
            order: 7,
            label: "Learn More",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 8,
            fontSize: 16,
            fontWeight: "600",
            height: 48,
            backgroundColor: "#1e40af",
            textColor: "#ffffff",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#f8fafc",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Member Benefits",
        description: "What you get",
        widgets: [
          {
            id: "cc2-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "cc2-2",
            type: "icon",
            order: 1,
            iconName: "Award",
            size: 64,
            color: "#1e40af",
            name: "Award Icon",
          },
          {
            id: "cc2-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "cc2-4",
            type: "text",
            order: 3,
            content: "Member Benefits",
            fontSize: 26,
            fontWeight: "600",
            textAlign: "center",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "cc2-5",
            type: "spacer",
            order: 4,
            height: 24,
            name: "Spacer",
          },
          {
            id: "cc2-6",
            type: "text",
            order: 5,
            content: "Exclusive networking events",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#1e40af",
            fontFamily: "Inter",
            name: "Benefit 1",
          },
          {
            id: "cc2-7",
            type: "spacer",
            order: 6,
            height: 8,
            name: "Spacer",
          },
          {
            id: "cc2-8",
            type: "text",
            order: 7,
            content: "Expert-led workshops & webinars",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#1e40af",
            fontFamily: "Inter",
            name: "Benefit 2",
          },
          {
            id: "cc2-9",
            type: "spacer",
            order: 8,
            height: 8,
            name: "Spacer",
          },
          {
            id: "cc2-10",
            type: "text",
            order: 9,
            content: "Premium resources & tools",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#1e40af",
            fontFamily: "Inter",
            name: "Benefit 3",
          },
          {
            id: "cc2-11",
            type: "spacer",
            order: 10,
            height: 8,
            name: "Spacer",
          },
          {
            id: "cc2-12",
            type: "text",
            order: 11,
            content: "Career advancement support",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#1e40af",
            fontFamily: "Inter",
            name: "Benefit 4",
          },
          {
            id: "cc2-13",
            type: "spacer",
            order: 12,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "cc2-14",
            type: "button",
            order: 13,
            label: "Continue",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 8,
            fontSize: 16,
            fontWeight: "600",
            height: 48,
            backgroundColor: "#1e40af",
            textColor: "#ffffff",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundColor: "#eff6ff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Ready to Join",
        description: "Become a member",
        widgets: [
          {
            id: "cc3-1",
            type: "spacer",
            order: 0,
            height: 60,
            name: "Top Spacer",
          },
          {
            id: "cc3-2",
            type: "icon",
            order: 1,
            iconName: "Users",
            size: 72,
            color: "#1e40af",
            name: "Users Icon",
          },
          {
            id: "cc3-3",
            type: "spacer",
            order: 2,
            height: 16,
            name: "Spacer",
          },
          {
            id: "cc3-4",
            type: "text",
            order: 3,
            content: "50,000+",
            fontSize: 36,
            fontWeight: "800",
            textAlign: "center",
            color: "#1e40af",
            fontFamily: "Inter",
            name: "Member Count",
          },
          {
            id: "cc3-5",
            type: "text",
            order: 4,
            content: "Active Members",
            fontSize: 16,
            fontWeight: "500",
            textAlign: "center",
            color: "#4b5563",
            fontFamily: "Inter",
            name: "Member Label",
          },
          {
            id: "cc3-6",
            type: "spacer",
            order: 5,
            height: 28,
            name: "Spacer",
          },
          {
            id: "cc3-7",
            type: "text",
            order: 6,
            content: "Join thousands of professionals who are already part of our community.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "#6b7280",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "cc3-8",
            type: "spacer",
            order: 7,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "cc3-9",
            type: "button",
            order: 8,
            label: "Join Community",
            variant: "custom",
            fullWidth: true,
            action: "close",
            borderRadius: 8,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#1e40af",
            textColor: "#ffffff",
            name: "Join Button",
          },
        ],
        layout: {
          backgroundColor: "#ffffff",
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
  {
    id: "premium-gradient",
    name: "Premium - Gradient",
    description: "3 screens: features, pricing and upgrade",
    category: "premium",
    style: "gradient",
    previewImage: premiumImg,
    screens: [
      {
        title: "Unlock Premium",
        description: "Get more features",
        widgets: [
          {
            id: "pg1-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "pg1-2",
            type: "image",
            order: 1,
            url: premiumImg,
            width: "100%",
            height: "200px",
            objectFit: "cover",
            borderRadius: 20,
            name: "Premium Image",
          },
          {
            id: "pg1-3",
            type: "spacer",
            order: 2,
            height: 28,
            name: "Spacer",
          },
          {
            id: "pg1-4",
            type: "text",
            order: 3,
            content: "Unlock Premium",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pg1-5",
            type: "spacer",
            order: 4,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pg1-6",
            type: "text",
            order: 5,
            content: "Get access to exclusive features and take your experience to the next level.",
            fontSize: 16,
            fontWeight: "400",
            textAlign: "center",
            color: "rgba(255,255,255,0.85)",
            fontFamily: "Inter",
            name: "Description",
          },
          {
            id: "pg1-7",
            type: "spacer",
            order: 6,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "pg1-8",
            type: "button",
            order: 7,
            label: "See Benefits",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#ffffff",
            textColor: "#7c3aed",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#7c3aed", position: 0 },
              { color: "#a855f7", position: 50 },
              { color: "#c084fc", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Premium Features",
        description: "What's included",
        widgets: [
          {
            id: "pg2-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "pg2-2",
            type: "icon",
            order: 1,
            iconName: "Crown",
            size: 72,
            color: "#fbbf24",
            name: "Crown Icon",
          },
          {
            id: "pg2-3",
            type: "spacer",
            order: 2,
            height: 24,
            name: "Spacer",
          },
          {
            id: "pg2-4",
            type: "text",
            order: 3,
            content: "Premium Features",
            fontSize: 26,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pg2-5",
            type: "spacer",
            order: 4,
            height: 24,
            name: "Spacer",
          },
          {
            id: "pg2-6",
            type: "text",
            order: 5,
            content: "Unlimited storage & exports",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#fef3c7",
            fontFamily: "Inter",
            name: "Feature 1",
          },
          {
            id: "pg2-7",
            type: "spacer",
            order: 6,
            height: 8,
            name: "Spacer",
          },
          {
            id: "pg2-8",
            type: "text",
            order: 7,
            content: "Priority customer support",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#fef3c7",
            fontFamily: "Inter",
            name: "Feature 2",
          },
          {
            id: "pg2-9",
            type: "spacer",
            order: 8,
            height: 8,
            name: "Spacer",
          },
          {
            id: "pg2-10",
            type: "text",
            order: 9,
            content: "Advanced analytics & insights",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#fef3c7",
            fontFamily: "Inter",
            name: "Feature 3",
          },
          {
            id: "pg2-11",
            type: "spacer",
            order: 10,
            height: 8,
            name: "Spacer",
          },
          {
            id: "pg2-12",
            type: "text",
            order: 11,
            content: "Ad-free experience",
            fontSize: 15,
            fontWeight: "500",
            textAlign: "center",
            color: "#fef3c7",
            fontFamily: "Inter",
            name: "Feature 4",
          },
          {
            id: "pg2-13",
            type: "spacer",
            order: 12,
            height: 32,
            name: "Bottom Spacer",
          },
          {
            id: "pg2-14",
            type: "button",
            order: 13,
            label: "See Pricing",
            variant: "custom",
            fullWidth: true,
            action: "next",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 52,
            backgroundColor: "#fbbf24",
            textColor: "#7c3aed",
            name: "Continue Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 180,
            stops: [
              { color: "#7c3aed", position: 0 },
              { color: "#6d28d9", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
      {
        title: "Choose Your Plan",
        description: "Subscription options",
        widgets: [
          {
            id: "pg3-1",
            type: "spacer",
            order: 0,
            height: 48,
            name: "Top Spacer",
          },
          {
            id: "pg3-2",
            type: "text",
            order: 1,
            content: "Choose Your Plan",
            fontSize: 28,
            fontWeight: "700",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Title",
          },
          {
            id: "pg3-3",
            type: "spacer",
            order: 2,
            height: 32,
            name: "Spacer",
          },
          {
            id: "pg3-4",
            type: "text",
            order: 3,
            content: "$9.99/month",
            fontSize: 40,
            fontWeight: "800",
            textAlign: "center",
            color: "#ffffff",
            fontFamily: "Inter",
            name: "Price",
          },
          {
            id: "pg3-5",
            type: "text",
            order: 4,
            content: "or $99.99/year (save 17%)",
            fontSize: 14,
            fontWeight: "500",
            textAlign: "center",
            color: "rgba(255,255,255,0.7)",
            fontFamily: "Inter",
            name: "Yearly Price",
          },
          {
            id: "pg3-6",
            type: "spacer",
            order: 5,
            height: 32,
            name: "Spacer",
          },
          {
            id: "pg3-7",
            type: "text",
            order: 6,
            content: "7-day free trial included",
            fontSize: 15,
            fontWeight: "600",
            textAlign: "center",
            color: "#fbbf24",
            fontFamily: "Inter",
            name: "Trial Info",
          },
          {
            id: "pg3-8",
            type: "spacer",
            order: 7,
            height: 40,
            name: "Bottom Spacer",
          },
          {
            id: "pg3-9",
            type: "button",
            order: 8,
            label: "Start Free Trial",
            variant: "custom",
            fullWidth: true,
            action: "custom",
            actionValue: "subscribe",
            borderRadius: 12,
            fontSize: 16,
            fontWeight: "600",
            height: 56,
            backgroundColor: "#ffffff",
            textColor: "#7c3aed",
            name: "Subscribe Button",
          },
          {
            id: "pg3-10",
            type: "spacer",
            order: 9,
            height: 12,
            name: "Spacer",
          },
          {
            id: "pg3-11",
            type: "button",
            order: 10,
            label: "Maybe Later",
            variant: "ghost",
            fullWidth: true,
            action: "close",
            fontSize: 14,
            fontWeight: "500",
            textColor: "rgba(255,255,255,0.8)",
            name: "Skip Button",
          },
        ],
        layout: {
          backgroundGradient: {
            enabled: true,
            type: "linear",
            angle: 135,
            stops: [
              { color: "#6d28d9", position: 0 },
              { color: "#4c1d95", position: 100 },
            ],
          },
          padding: 24,
          verticalAlignment: "center",
          safeAreaTop: true,
          safeAreaBottom: true,
        },
      },
    ],
  },
];
